### PR TITLE
FE#49: Change URL to FE's forgot password URL.

### PR DESCRIPTION
**Pull request by logicplace**
Also passes username now.

Didn't test this cause my local backend isn't working right now. :(

### CODE REVIEW

**Comment by scotte216** [comment]
I got the following email: 

http://localhost/forgot.html?username=username&id=e5b46f42-c4e7-48fa-8252-09a76ff8b64f

Looks good to me! Is this what you expected, @logicplace?

**Comment by logicplace** [comment]
Yeah that's what I expect, looks good.

**Comment by SoySauceLabs** [comment]
Agreed, looks good. I would hit the button right now, but I know it's going to break at least one test, so I can fix (and merge) that a little later unless someone else gets to chance to patch it up. 📌

**Comment by SoySauceLabs** [comment]
oh wait, derp, checks have passed....

**Pull request merged**
