### PR TITLE
Be#29 store user auth token

### PR DESCRIPTION
**Pull request by ghost**
Check it!

### CODE REVIEW

**Comment by scotte216** [comment]
A couple questions:
1) Any chance you can add a few test to cover these new functions? There should be good examples for other queries in the project already. See tests/tests.py for examples.

2) Any chance you can set up your query to use 'prepared statements'? See https://datastax.github.io/python-driver/getting_started.html#id2 for an example.

**Comment by kbrimm** [comment]
This is due today - how's the unit testing integration going?

**Comment by SoySauceLabs** [comment]
Ahhh, so a little update:

I was late to the party here (my bad), but I've given some guidance to Eric on adding some other goodies to this to get it up to speed (namely the remainder of the endpoints so that we can [a] test them, and [b] use them 😺 ).

The train's chugging along!

**Comment by SoySauceLabs** [comment]
Ship It!

**Pull request merged**
